[package]
name = "charls-sys"
version = "0.1.0"
authors = ["Douglas Yau <dy@dicomserver.net>"]
edition = "2021"
description = "Bindgen bindings to charls"
build = "build.rs"
links = "charls"

[dependencies]

[build-dependencies]
bindgen = "0.65"
cmake = "0.1"

[features]
default = []
static = []
gdcm = []
